import Head from "next/head";
import Header from "@/components/layouts/Header";
import Campaigns from "@/components/Campaigns";

export default function Index() {
  return (
    <>
      <Head>
        <title>SJWBurger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>
      <div>
        <Header />
        <Campaigns />
      </div>
    </>
  );
}
